fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '5.2.0'
    archive:
      repo: 'puppet/archive'
      ref: '3.2.1'
    augeas_core:
      repo: 'puppetlabs/augeas_core'
      ref: '1.0.4'
  symlinks:
    bamboo: "#{source_dir}"
